development:
  adapter: postgresql
  encoding: unicode
  database: shoes_development
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: shoes_test
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: shoes_production
  pool: 5
  timeout: 5000

